/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gui;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;

import java.net.URL;
import java.util.ResourceBundle;

public class MainApp extends Application
{

    public static void main (String[] args)
    {
        Application.launch(MainApp.class, args);
    }

    @Override
    public void start (Stage primaryStage) throws Exception
    {
        primaryStage.setTitle("JRD Keepalive");

        //load layout for main window
        FXMLLoader loader = new FXMLLoader();
        URL styleResource = getClass().getResource("/MainApp.fxml");
        loader.setLocation(styleResource);
        AnchorPane rootLayout = loader.load();

        Scene scene = new Scene(rootLayout);
        primaryStage.setScene(scene);

        primaryStage.show();
    }
}
