/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gui;

import javafx.application.Application;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;
import script.MouseAutomation;

import java.awt.*;
import java.io.File;

public class MainApp extends Application
{
    private AnchorPane rootLayout;

    public static void main (String[] args)
    {
        Application.launch(args);
    }

    @Override
    public void start (Stage primaryStage) throws Exception
    {
        primaryStage.setTitle("JRD Keepalive");

        //load layout for main window
        FXMLLoader loader = new FXMLLoader();
        loader.setLocation(new File("src/main/java/gui/MainApp.fxml").toURI().toURL());
        rootLayout = loader.load();

        Scene scene = new Scene(rootLayout);
        primaryStage.setScene(scene);

        primaryStage.show();
    }
}
